---

- include: apt_install.yml
  when: ansible_pkg_mgr == 'apt'

- include: yum_install.yml
  when: ansible_pkg_mgr == 'yum'

- include: openbsd_install.yml
  when: ansible_pkg_mgr == 'openbsd_pkg'

- include: freebsd_install.yml
  when: ansible_pkg_mgr == 'pkgng'

- include: configure.yml
