---

- name: Setup OpenBSD specific variables (set_fact)
  set_fact:
    tor_DataDir: /var/tor
    tor_PidDir: /var/tor/pids
  tags: configure

- name: Gather current tor install state (OpenBSD)
  command: "pkg_info -qe tor-*"
  ignore_errors: yes
  register: torpkg

# the following task fails HARD on purpose (if ports are not there)
# TODO: add an opt-in var that takes care of installing ports
- name: Install tor from ports (OpenBSD)
  sudo: yes
  shell: "cd /usr/ports/net/tor && make install"
  when: torpkg.rc == 1

- name: Gather current system-wide file descriptor limits (OpenBSD)
  shell: "sysctl kern.maxfiles|cut -d= -f2"
  register: currentlimits

- name: Ensure system-wide runtime file descriptor limits are reasonable (OpenBSD)
  sudo: yes
  command: "sysctl kern.maxfiles=20000"
  when: currentlimits.stdout|int < 20000

- name: Ensure system-wide persistent file descriptor limits are reasonable (OpenBSD)
  sudo: yes
  lineinfile: dest=/etc/sysctl.conf regexp=^kern.maxfiles line="kern.maxfiles=20000" create=yes
  when: currentlimits.stdout|int < 20000

- name: Ensure Tor process file descriptor limits are reasonable (OpenBSD)
  sudo: yes
  lineinfile: "dest=/etc/login.conf line='{{ tor_loginclass }}::openfiles-max=13500::tc=daemon:'"
  #TODO
  #notify: restart tor

- name: Ensure 'tor_user' has appropriate login class set (OpenBSD)
  sudo: yes
  user: name={{ tor_user }} login_class={{ tor_loginclass }}
  #TODO 
  #notify: restart tor
