---
#- name: restart tor
#  service: name=tor state=restarted

- name: stop-and-disable tor
  sudo: yes
  service: name=tor state=stopped enabled=no

- name: restart apparmor
  sudo: yes
  service: name=apparmor state=restarted

- name: systemctl daemon-reload
  sudo: yes
  command: systemctl daemon-reload
